### ISSUE TITLE
4:3 aspect correction

### ISSUE THREAD

**Issue by Kappa971** [fabiangreffrath/wolf4sdl#34]
The game is displayed in the wrong aspect ratio:
1. at 320x200 and multiples, it is displayed in 16:10
2. at 320x240 and multiples, it is displayed in 4:3 but the image isn't displayed correctly (everything looks wider). Menus are clipped, they are always displayed in 16:10 but with a big black bar below.

**Comment by fabiangreffrath** [comment]
Yes, right. I should probably apply aspect ratio correction as we do in Doom source ports and get rid of the 320x240 mode entirely.

**Comment by Kappa971** [comment]
Would be great. In addition, you could make the choice of resolutions easier:
1. by choosing between low resolution (320x200) and high resolution (640x400) scaling to the native screen resolution, 
2. or simplify the choice of resolutions in another way while maintaining the highest resolutions.

This would make wolf4sdl a valid alternative to ECWolf.
