### ISSUE TITLE
Music plays too fast

### ISSUE THREAD

**Issue by Kappa971** [fabiangreffrath/wolf4sdl#35]
I compiled wolf4sdl on Windows and the music plays very fast (and gets high-pitched).
At first I thought it was due to the monitor's refresh rate (greater than 70hz) but even changing the monitor's refresh rate to 60hz, the music goes the same way. I tried on an older PC (Intel Core I7 860) and there the music goes almost at normal speed but it is still too fast, so I guess the problem is related to the CPU speed. The sound effects work well.

**Comment by fabiangreffrath** [comment]
Does setting a different sample rate on the command line help, e.g. `--samplerate 48000`?

**Comment by fabiangreffrath** [comment]
@Kappa971 Could you please check if this commit fixed the issue for you?
https://github.com/fabiangreffrath/wolf4sdl/commit/4880f05333b6e8cccb1ccee2bb49b781157433b8

**Comment by Kappa971** [comment]
> @Kappa971 Could you please check if this commit fixed the issue for you? [4880f05](https://github.com/fabiangreffrath/wolf4sdl/commit/4880f05333b6e8cccb1ccee2bb49b781157433b8)

Yes, this fixed the problem, thanks
